namespace: three-tier-app

frontend:
  replicas: 2
  image: my-frontend:1.0
  servicePort: 80

backend:
  replicas: 2
  image: my-backend:1.0
  servicePort: 8080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

database:
  image: mysql:8
  user: mysql
  password: password
  dbName: mydb
  storage: 1Gi

ingress:
  enabled: true
  host: myapp.local

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70
