apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.database.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"
