apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.database.user | b64enc }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
